### ISSUE TITLE
Conda installed "get_version" with version number "0.0.0"

### ISSUE THREAD

**Issue by LustigePerson** [flying-sheep/get_version#6]
When installing get_version (2.1) from conda, `get_version.__version__` is reported as 0.0.0.

**Comment by flying-sheep** [comment]
OK… what’s get_version’s log output? Just set the log level to info before importing and it’ll tell you.

Also you need to use [markdown](https://guides.github.com/features/mastering-markdown/) for formatting your text here.

**Comment by LustigePerson** [comment]
Log Output:
```python
>>> import get_version
INFO:get_version:dirname: Trying to get version of get_version from dirname C:\Users\FOO\AppData\Local\Continuum\anaconda3\envs\test\Lib\site-packages
INFO:get_version:dirname: Failed; Does not match re.compile('get[_-]version-([\\d.]+?)(?:\\.dev(\\d+))?(?:[_+-]([0-9a-zA-Z.]+))?$')
INFO:get_version:git: Trying to get version from git in directory C:\Users\FOO\AppData\Local\Continuum\anaconda3\envs\test\Lib\site-packages
INFO:get_version:git: Failed; directory is not managed by git
INFO:get_version:metadata: Trying to get version for get_version in dir C:\Users\FOO\AppData\Local\Continuum\anaconda3\envs\test\lib\site-packages
INFO:get_version:metadata: Succeeded
```

In `C:\Users\FOO\AppData\Local\Continuum\anaconda3\envs\test\lib\site-packages`there is a directory called `get_version-0.0.0.dist-info`.
Is get_version working with conda/ anaconda packages in general?

I just tested this in a plain environment.

**Comment by flying-sheep** [comment]
Well, it behaves as it should locally, the problem is the way it behaved when the conda package was built. The remaining question: Did they do something weird (=it’s their bug) or did I not think of something (=it’s my bug). This is probably where their build lives: https://github.com/conda-forge/get_version-feedstock
