### ISSUE TITLE
flit+get_version requires all dependencies to be installed at build time

### ISSUE THREAD

**Issue by grst** [flying-sheep/get_version#8]
I just noted that using `get_version` with `flit` requires all package dependencies to be installed at build time. This is because `flit` tries to derive the version from AST-parsing, if that fails it imports the module (and therefore all dependencies). See [flit source code](https://github.com/takluyver/flit/blob/969117152279a58c5e887b8734873ec62660febc/flit/common.py#L107-L113). 

This is, for instance, annoying when building conda packages (all dependencies need to be included in the `host` section of `meta.yml`). 

@flying-sheep, do you think there would be an elegant solution to this? The only thing I could think of are conditional imports in the `__init__.py` file, i.e. not importing dependencies when the package is imported from flit: 

**__init__.py**
```python
# To avoid that all dependencies need to be installed at build
# time:
import sys
if "flit" not in sys.argv[0]:
    from .foo import bar
    from .bar import foobar    
```

(However, in its current version, it's not very robust and might have side-effects)

**Comment by flying-sheep** [comment]
That’s even more elegant than what I came up with…

This issue is takluyver/flit#253
